gmail_user: "federicocomel1@gmail.com"
gmail_password: "sxut pnec phde lhyb"
qasa_email: "federicocomel1@gmail.com"
qasa_password: "hypgu1-zegriz-marfoK"
message_to_owner: |
  Hi! I’m Fede, an incoming Master’s student at KTH. I’m very interested in the apartment and would love to schedule a video call as soon as possible to view it. If everything looks good, I’d be happy to move forward quickly with the contract.

  Here’s my number in case it’s easier to reach me: +39 388 466 1392.

  Looking forward to hearing from you!
  